### ISSUE TITLE
Ping example doesn't match that on the website

### ISSUE THREAD

**Issue by mandreyel** [actix/actix#214]
Not sure if this should be an issue but I was reading the [docs](https://actix.rs/book/actix/sec-1-getting-started.html) and then followed the link to the example's code on github and noticed that they differed. Which is considered more up-to-date (and thus the best practice)?

**Comment by DoumanAsh** [comment]
Well examples is more up to date

**Comment by andor44** [comment]
I just spent a good hour scratching my head why the examples on the official (!) website don't work. I was on the verge of giving up and dropping actix altogether before I figured I'd give the issue tracker a look. While the differences might seem minor to a seasoned user of Actix, in reality the differences are massive and not something a newcomer will be able to guess by themselves. I highly recommend updating the website to better reflect the state of the project to avoid turning away new users.

**Comment by Firstyear** [comment]
@andor44 Hi there. Recently I have been working really hard with @DoumanAsh and @rivertam to update the documentation of the project - this means the book, website, and the API level documentation. If you can point us to specific areas of complexity you are having issues with that would really help us to understand what we need to improve. 

A source of confusion could be that the book examples have the ability to "mask" lines, so that we can focus on example content. To demonstrate, some example code I recently wrote looks like:

```
# extern crate actix;
use actix::prelude::*;

struct MySyncActor;

impl Actor for MySyncActor {
    type Context = SyncContext<Self>;
}

# fn main() {
# System::new("test");
let addr = SyncArbiter::start(2, || MySyncActor);
# }
```

Notice the '#"? They allow the code to be "hidden" in the final rendered book, but they still "compile" and run for the purposes of cargo test. So every example in the book *must* compile and run. If you look in the examples, in the top right there is a pair of "double arrows". Selection of this will show you the hidden lines, so you can copy the full example. 

In general I agree that the project needs to improve it's documentation efforts from all parties, and especially the API level documentation that tends to be extremely sparse. If you want to help, I'd appreciate your feedback and contribution!

**Comment by andor44** [comment]
@Firstyear sure thing, two points jump to mind:

First, the root cause of my frustration was, ironically, not even actix itself but futures (ha). Because the documentation hid the `use futures::Future;` import its methods were not available on `actix::Request`, so I skipped `map/map_err` since I thought that was superfluous given my Handler wasn't returning a `Result`. That left me with really hard-to-understand type inference errors such as:

```
error[E0271]: type mismatch resolving `<actix::prelude::Request<MyActor, Foo> as futures::future::Future>::Error == ()`
  --> src/main.rs:36:5
   |
36 |     Arbiter::spawn(request);
   |     ^^^^^^^^^^^^^^ expected enum `actix::MailboxError`, found ()
   |
   = note: expected type `actix::MailboxError`
              found type `()`
   = note: required by `actix::Arbiter::spawn`
```

In retrospect this is not really the fault of actix itself, although I'd advise on not omitting the `Future` import in the example.

Second, and I realize this is a bit more vague: the guide is sparse on details on what `Arbiter` and `System` are, what exactly they do and especially how they relate to tokio. The guide mentions tokio only in passing, whereas the ping example code in the repo has a `tokio::spawn` call. After my first reading of the guide I was hoping I didn't need to know tokio too well and that it was only an internal implementation detail but that seems not to be the case. I realize teaching tokio is already hard in and of itself, but if it's a necessary piece of knowledge then as a new actix user it'd be really helpful to know how these actix concepts relate to tokio at a high level.

**Comment by rivertam** [comment]
@fafhrd91 this is some evidence actix should include `futures::Stream` and `futures::Future` in the prelude (which I briefly touched on yesterday)

**Comment by fafhrd91** [comment]
@rivertam ok, could you make PR

**Comment by Firstyear** [comment]
I agree, I think it also highlights a need to "human test" that our examples copy-paste, and build up to a working .rs file, without the code expansion options.

**Comment by mandreyel** [comment]
Personally, I'd prefer for the code examples to always specify what is included, even if sacrificing brevity. Omitting `main` and similar is fine with me.

**Comment by rivertam** [comment]
@andor44 I should have mentioned this yesterday but was focused on that one point.

We recently updated the [Arbiter page](https://actix.rs/book/actix/sec-5-arbiter.html) in the book. The abstraction isn't perfect, but if you're doing normal things within Actix, you shouldn't need to understand Tokio that well. Keep in mind, you will still need to understand asynchronous code -- there's no way around that. However, almost anything you would want to do with tokio is covered by `Arbiter`/`Context`. Check out the book and let us know if there are still confusions.

**Comment by Firstyear** [comment]
@rivertam I think the issue is if we copy-paste examples they don't build to working code. So I think that we should check this soon.

**Comment by rivertam** [comment]
@Firstyear Copy/paste as in without expanding the hidden lines? That's not a concern of mine. If the example actually doesn't run as written, that's what concerns me. Am I understanding the issue here?

**Comment by negcx** [comment]
@rivertam I can't get the examples to run when following along, or when copying and pasting from the examples directory.

**Comment by rivertam** [comment]
@negcx Yeah, I'm not super in-tuned with the problem. I'm not saying there isn't one. If examples in the examples directory doesn't compile, that's probably a problem that needs to be fixed. Posting the error messages would be good, though. I presume the examples all compiled and ran when they were originally written, but that might not be true (I didn't write them).

If the issue is literally just `use futures::{Future, Stream}`, I believe they all will work in this regard, so that doesn't seem to me like it would be the issue in this case.
