### ISSUE TITLE
Recipient transforms

### ISSUE THREAD

**Issue by rivertam** [actix/actix#229]
I'd love to see a set of features that would enable me to modify recipients sort of like `Stream`s only on the other side.

An example of a transform:

```rust
// assume `some_addr` is the `Addr` for a `Handle<u32>`
let recipient: Recipient<u32> = some_addr.recipient();
let fake_recipient: Recipient<u64> = recipient.transform(|num: u64| num as u32);
```

This transform would be kind of like an "unmap"; the opposite of a map. Now when you `fake_recipient.send(0u64)`, it first runs it through the transform and then feeds it back to `recipient` as a `u32`. I think if I were to design and implement this today, I'd implement it to return an `Option<u64>` so we can also filter without doing multiple steps. e.g.

```rust
let evens_recipient = recipient.transform(|num: u64| {
    if num % 2 == 0 {
        Some(num as u32)
   } else {
        None
   }
});
```

My usecase involves one "fast" stream of type erased messages over a protocol. In a way, they're kind of like API requests as strings. Then I have actors that want to listen to specific events which happen less frequently. So maybe I'll have something like this (tons of details redacted to avoid unnecessary information):

```rust
#[derive(Clone)]
struct ApiMessage {}

#[derive(Clone)]
struct DoFoo {}

impl DoFoo {
     pub fn from_api_message(m: &ApiMessage) -> Result<DoFoo, ParseError> { /* ... */ }
}

struct Messenger {
    message_recipients: Vec<Recipient<ApiMessage>>,
}

impl Actor for Messenger {}

impl Handler<SubscribeToApiMessage> for Messenger {
   fn handle(&mut self, sub: SubscribeToApiMessage, _ctx: Self::Context) -> Self::Result {
       // keep all subscribing recipients in vec
       self.message_recipients.push(sub.recipient);
   }
}

struct FooDoer {}
impl Actor for FooDoer {}
impl Handler<DoFoo> for FooDoer {}
```

then later I'd like to be able to do something like this:

```rust
let foo_doer: Recipient<DoFoo> = foo_doer_address.recipient();
messenger_address.send(SubscribeToApiMessage {
    recipient: foo_doer
        .transform(|msg: ApiMessage| match DoFoo::from_api_message(&msg)
            Ok(do_foo) => Some(do_foo),
            Err(e) => {
                // no "error" per se in this case, it's just not a `DoFoo` message, so we filter it out
                None
            }
        })
})
```

Is something like this possible now? I know I could just have `FooDoer` impl `Handle<ApiMessage>` and do the mapping and filtering there, but in my case this would lead to a ton of repetitive code as there are a lot of types of `ApiMessage`.

I do have one concern regarding implementation, which is where the transform function would live and where it would be run. I would imagine it would belong either on the `Recipient` or the inner `Sender`.

**Comment by DoumanAsh** [comment]
I don't think it is good idea to treat `Recipient` itself as `Stream` and provide similar interface to map one value to another.

This is should be done on receiving end when necessary.
You basically change the type of message that `Recipient` is used to send over.

I'm not sure what's point of that, when you can get recipient with needed type from `Addr` itself.
Your idea seems very weird because actix's messages are supposed statically known.

This belongs to Future plans issue https://github.com/actix/actix/issues/224
But to be honest I think it is clearly unnecessary API

**Comment by rivertam** [comment]
I'm fine with it because I think I found a workaround (returning a `Stream<ApiMessage>` that can then be fed to an address/recipient in a `.map`).

To clarify, the point would be to avoid having to write the conversion from `ApiMessage` to `DoFoo` on `FooDoer`, or any other `Handler<DoFoo>`s. In fact, I want `FooDoer` and anything else that *consumes* `DoFoo` but be blissfully unaware of `ApiMessage`, which is a low-level protocol construct.

I have a lot of types of messages that map to a bunch of actors (many-to-many, but not all all-to-all) but they all flow through the protocol which I want to be able to swap in and out. Basically I'm trying to avoid having `FooDoer` be even aware of `ApiMessage`. To me, `ApiMessage` is actually more like a trait that represents anything you can turn a `Packet` (struct with just data) into. So I have a protocol in the middle that can read across any transport, and I'd like to avoid having to write out like

```rust
do_foo_subscribers: Vec<Recipient<DoFoo>>,
do_bar_subscribers: Vec<Recipient<DoBar>>,
// ...
```

and instead just have

```rust
api_message_subscribers: Vec<Recipient<ApiMessage>>,
```

but being able to implement `Handler<DoFoo>` and `Handler<DoBar>` on the actual subscribers.

Hopefully that makes more sense. I think it's unnecessary but convenient and powerful in a way that can still be quite performant. It's a form of contract polymorphism that I think has a place in an actor model system, but I won't continue to push it if you still think it's too weird or unnecessary.

**Comment by DoumanAsh** [comment]
@rivertam The problem is that `Recipient` is bound to the message type, and without taking back `Addr` you cannot really change the type of message

>To clarify, the point would be to avoid having to write the conversion from ApiMessage to DoFoo on FooDoer, or any other Handler<DoFoo>

The best would be for `ApiMessage` to be enum with all possible variants or trait object(which would be actual polymorphic)

Recipient can be only created from `Addr` and for actor that implements `Handler<ApiMessage>`, your changes would require to break current approach

**Comment by najamelan** [comment]
@rivertam Why do you want to filter messages. You can deliver them to the right actor. Have actors subscribe to exactly the type of messages they are interested in. Next you dispatch the incoming messages. I do it like [this](https://github.com/ekke-rs/ekke_io/blob/2d2f9ff7315fe922c4ac2380a33d6846121e6d30/src/rpc.rs#L210). This calls the matcher, which is a callback that the application has to provide to map string rpc names to rust types, to deserialize the messages to the correct type. An example of the [matcher](https://github.com/ekke-rs/ekke_core/blob/05a4fdb6ea5385cfe463410be4c17278be3d89c5/src/ekke_core/lib.rs#L66). The rest of the dispatching happens in [rpc.deser_into](https://github.com/ekke-rs/ekke_io/blob/2d2f9ff7315fe922c4ac2380a33d6846121e6d30/src/rpc.rs#L121). I store a [hashmap](https://github.com/ekke-rs/ekke_io/blob/2d2f9ff7315fe922c4ac2380a33d6846121e6d30/src/rpc.rs#L29) that maps the typeid of the Message to an [Any pointer](https://doc.rust-lang.org/std/any/index.html) representing the recipient. I deliberately only allow one Actor to be registered for every service. Otherwise you could store map to a vector of recipients.

Something very similar can also be done conveniently by using the crate [actix_broker](https://crates.io/crates/actix-broker).

If there's something you don't understand, I'm on the actix gitter as well, or here: #najamelan:matrix.org.

**Comment by rivertam** [comment]
@najamelan 

> Why do you want to filter messages. You can deliver them to the right actor. Have actors subscribe to exactly the type of messages they are interested in.

I am doing that, actually. I don't think it should be necessary, but I think it's marginally better for performance to do pretty much exactly what you're doing.

The problem, which you've also encountered, is now you can't store the handlers as `Recipient<ActualMessage>`. You've solved this by casting them to `std::any`, deferring the typechecking to runtime. It also couples your deserialization logic with the internal handler mechanism, though I think you've done a pretty good job of exposing this cleanly.

`std::any` is a pretty reasonable approach. I thought you'd have to dip into unsafe to do that. While I don't like typeids in general, I'm basically doing that at the protocol level so it's not that bad. But yeah, it would be good to be able to use `Recipient<ActualMessage>` or at least `Recipient<any>` or similar rather than just `Box<dyn any>`. It would be more descriptive and require less dynamic typechecking code.

**Comment by najamelan** [comment]
Well, it's not an easy thing in a strict static language. This is my first solution to this problem, but maybe there will be improvements later (in elegancy). Note btw that Addr will not allocate on the heap but Recipient will, if you care about perf at the point of rtti.

The thing is, if you get data of an unknown type (serialized) at runtime, there is no way you can deserialize that into a type safely without doing a runtime check. You want the performance, do it with unsafe and crash... I don't see any theoretical alternatives.

Sure, there could be syntactic sugar however.

**Comment by rivertam** [comment]
> The thing is, if you get data of an unknown type (serialized) at runtime, there is no way you can deserialize that into a type safely without doing a runtime check

Yes, but it can happen in one go. It happens that that approach would be more ergonomic for my project, and I think it would be for yours as well. I'm not really considering performance here, but what I'm suggesting would result in much less code to maintain and imo would be more readable.

**Comment by najamelan** [comment]
Ben Berman:
> Yes, but it can happen in one go.

I'm not exactly sure what you mean by this, but I the only thing in my code that varies is the matcher function that every application using the rpc system must provide just once. I will surely reduce that to a macro taking just a list of message types like this:
```rust
service_map!
(
    ServiceA,
    ServiceB,
    ServiceC,
    ...
)
```
Just haven't come round to it yet because as you saw, for the moment only one service in my map, so I had other priorities.

With actix-broker it comes down to every actor just subscribing to their Message type. Note also that the reason for the service map is that you need to know the type in order to serialize, at least with serde. So somewhere a list must exist.

**Comment by rivertam** [comment]
To be honest, I'm pretty confused about a lot of the code, so I can't really respond properly. I don't think Actix broker is really at all what I'm talking about, but I can't exactly tell because Actix broker confuses me more generally -- it seems like you subscribe to an actor instance from within the actor, but there can be multiple subscriptions? I'd need to see a practical example I think.

I do want to add that `futures::sink::Sink` has something like this: https://docs.rs/futures/0.1.25/futures/sink/trait.Sink.html#method.with
