### ISSUE TITLE
Allow to return a future and `wait` for it

### ISSUE THREAD

**Issue by s-panferov** [actix/actix#237]
Right now we have a MessageResponse implemented for Futures and ActorFutures [with a `ctx.spawn` call inside](https://github.com/actix/actix/blob/8b2b75cd8f7c737cd664d0d07496c5d6bb0d737c/src/handler.rs#L162). I encountered a case when I need a counterpart with a `ctx.wait` call (running a milti-step transaction in my database which should not be mixed with any other messages).

Right now I'm doing this using a wrapper:

```rust
use actix::dev::{MessageResponse, ResponseActFuture, ResponseChannel};
use actix::prelude::*;

pub struct WaitFut<A, I: 'static, E: 'static>
where
    A: Actor,
    A::Context: AsyncContext<A>,
{
    pub fut: ResponseActFuture<A, I, E>,
}

impl<A, M, I: 'static, E: 'static> MessageResponse<A, M> for WaitFut<A, I, E>
where
    A: Actor,
    M: Message<Result = Result<I, E>>,
    A::Context: AsyncContext<A>,
{
    fn handle<R: ResponseChannel<M>>(
        self,
        ctx: &mut A::Context,
        tx: Option<R>,
    ) {
        ctx.wait(self.fut.then(move |res, _, _| {
            if let Some(tx) = tx {
                tx.send(res);
            }
            fut::ok(())
        }));
    }
}
```

This does not feel ergonomic, maybe there is a better way of doing the same thing better?

**Comment by DoumanAsh** [comment]
I don't think there is any other way, at least as long as you need to prevent your actor from processing any other message or future that is scheduled by `Context::spawn`

You cannot actually `wait` for future because it would  be block event loop, that's why there is `Context::wait` which adds future to special queue that prevents other items to be processed until it is cleared
