### ISSUE TITLE
Serialisation of system

### ISSUE THREAD

**Issue by kingoflolz** [actix/actix#24]
I'm wondering if you will be interested in adding support for serializing the state of an entire actor system. How I see it could be implemented is first waiting for the completion of processing of all currently executing Handlers, preventing new ones from starting, then write out the state of each arbiter and the state of each actor within it, including their inboxes.

This will be pretty difficult to implement, but I will be interested in doing so.

**Comment by fafhrd91** [comment]
that sounds interesting. i'd prefer to develop this system as separate library, later we can decide about merging to actix. you could do development within actix organization if you like.

**Comment by kingoflolz** [comment]
Cool, this is more of a long-term and low priority project, so it is probably not going to see much progress until all the urgent stuff in my project have been sorted out

**Comment by fafhrd91** [comment]
another idea, instead of serialize runtime we can create two systems.

1. declarative initialization, this system should simplify create complex topologies of actors
2. persistent system, so actors could persist state in storage

I think this should be simpler than runtime serialization.
what do you think?

**Comment by fafhrd91** [comment]
this won't happen in near future, and should be implemented as external library
