### ISSUE TITLE
Non local type dependency

### ISSUE THREAD

**Issue by PlaneB** [actix/actix#287]
If one implements an actor on a parameterized struct `Act1<T>` and wants it to communicate with another actor `Act2`, then `Act2` needs the address of `Act1<T>`. Unfortunately this implies that `Act2` will have a dependency on 'T' to, so the signature of `Act2` needs to be changed into `Act2<T>` as a result. Now this second actor and in fact all actors that are connected to `Act1<T>` through the message graph, now have to be changed to depend on T, too. 

But they don't really depend on T, do they? I mean 'T' is not involved as long as it does not influence the content of any message between the two actors. In theory at least. In Rust this does not seem to work.

So the question/issue is: Is this really necessary or is there a way around this? 

Or seeing it differently: If I change the signature of one actor `Act1` into `Act1<T>`, say because the codebase advances, then I also have to change the signatures of all actors that communicate with `Act1` (now `Act1<T>`) and also inductively of all actors that communicate with those actor and so on. This is quite a big implementation overhead, as livetimes need to be considered to. Moreover it somehow feels to play against the locality property of the actor model. Therefore some clever trick to get around that is very much appreciated.

**Comment by cerceris** [comment]
Don't over-complicate your program's design. Take a look at `Recipient` https://docs.rs/actix/0.8.3/actix/struct.Recipient.html.

**Comment by PlaneB** [comment]
Yes, not making the program overly complicted, is exactly the point. Can you give a bit more detail, how Recipient solves the problem?

**Comment by cerceris** [comment]
Briefly, `Addr` is parametrized with Actor type, `Recipient` is parametrized with Message type. Thus the latter can be used to specify "interface" / "protocol" / whatever you name it for inter-actor communication.

**Comment by fakeshadow** [comment]
It's necessary. `Addr` is bound to Actor type because an actor can handle different types of message and a channel is used to let your messages reach actor. In Rust most channel pattern can only handle one type(e.g `std::sync::mpsc::channel::<u8>()`). 

This lead to all types of messages are boxed as trait objects generic Actor type so they share the same size and type to fit them in said channel. The Actor type is needed to tell these trait objects what/which actor handler method is called on specific message type. 

This is other way to do further rust type erasure but it's not in the scope of actix so I would not go into it. You can look up the keyword and decide for yourself.
