### ISSUE TITLE
A crash inside a SyncArbiter actor: How restart?

### ISSUE THREAD

**Issue by mamcx** [actix/actix#301]
I have a actix-web API project, and if the code inside the SyncArbiter crash, the API get in a limbo state. I start with:

```rust
pub fn run_server() -> Result<(), DbErr> {
    let sys = actix_rt::System::new("Api");
    let pool = Db::open_server(None)?;
    let address: Addr<DbExecutor> = SyncArbiter::start(4, move || DbExecutor(pool.clone()));

    let mut server = HttpServer::new(move || {
        App::new()
            .data(address.clone())

impl From<actix::MailboxError> for ServiceError {
    fn from(error: actix::MailboxError) -> ServiceError {
        ServiceError::InternalServerError(format!("{}", error))
    }
}
```
Now, maybe a .unwrap fail. Then I get LATER i get:

`InternalServerError("Mailbox has closed")
`
When this error show up, is unclear what cause it (I wish the MailboxError have attached the cause). And from it ALL THE REQUESTS WILL FAIL with the same error.

I wish the error only be for the request that cause it only, not for all. Exist a way to catch, handle or restart it?

**Comment by cptrodgers** [comment]
A thread is panic will hard to catch it. When crash is happened, the actor will be destroyed, (i guest). So when you trying to send a message to this actor, basically, it should be closed. I'm also using actix and actix web in production, I handle panic with 2 things:
1. Don't `unwrap`. Return maximum errors that you can handle by `?` and `From` trait. This is similar to Golang.
2. Catching an panic in main project with the hook of `std` because of you can have some errors that can not handle. Rust will add the information - what make the your app is panic - in backtrace soon. See code below.
```rust
    std::panic::set_hook(Box::new(|panic_info| {
        info!("Catch a panic");
        error!("{}", panic_info);
        // Do some stuff here, report to sentry, your log, or your email.
    }));
```

**Comment by fakeshadow** [comment]
The answer would be not panic inside sync actor handler. 

Your handler method would borrow actor and making it unwindsafe would not be what everyone want.
