### ISSUE TITLE
Shouldn't it be Addr<MessageType> instead of Addr<ActorType>?

### ISSUE THREAD

**Issue by ufoscout** [actix/actix#364]
Hi guys,

I don't know whether this is feasible in Rust, anyway, one of the advantages of an actor framework is decoupling different pieces of an application, so I expected that the address of an Actor would not be bound to the actor type, but instead to the type of messages that can be sent on it.

So my "decoupled code" could look like (pseudo code):
```rust

fn main() {
    let address: Addr<StringMessage> = match something {
         MyType::TypeA => ActorA::create(||...),
         MyType::TypeB => ActorB::create(||...),
         MyType::TypeC => ActorC::create(||...)
    };

    // Imagine this in a component that knows nothing about ActorA - ActorB - ActorC
    let string_message = "blablabla".into();
    address.do_send(string_message);
}
```

Similar behaviour can already be achieved, in a more verbose way, by moving the code that uses the `address` in a generic function, for example:
```rust
fn main() {
    match something {
         MyType::TypeA => send(ActorA::create(||...)),
         MyType::TypeB => send(ActorB::create(||...)),
         MyType::TypeC => send(ActorC::create(||...))
    };
}

fn send<A: Actor + actix::Handler<StringMessage>>(
    address: Addr<A>,
) where
        <A as Actor>::Context: ToEnvelope<A, StringMessage> {
    let string_message = "blablabla".into();
   address.do_send(string_message);
}
```

anyway, this approach is by far more verbose and unpractical if there is more than one actor type to be determined dynamically.

**Comment by Jonathas-Conceicao** [comment]
What about when the Actor can receive more than one type of message? How would the `Addr` signature go? A `enum` to the possible messages? Or should we have multiple `Addr` to the same `Actor`? I my use cases for actors most of them can receive different types of messages, so `Addr<ActorType>` seems better than `Addr<MessageType>`.

However I do see how this alternative approach could be more interesting to better abstract and isolate the Actor's type itself. I think it could be nice if we offer a better way to support it.

**Comment by ufoscout** [comment]
@Jonathas-Conceicao 
I did not think exactly about how it should be implemented, as I said, I am not even sure if this can be achieved in rust.

**Comment by GeorgeHahn** [comment]
This sounds a lot like the existing [`Recipient`](https://docs.rs/actix/0.10.0-alpha.2/actix/struct.Recipient.html) type

**Comment by fakeshadow** [comment]
I'm also thinking something like this but for a different reason.
One advantage of staticly type only one message to an actor is that we can reduce the heap allocation of every message dispatch since no trait object is needed.
The downside is just like Jonathas-Conceicao pointed out it adds boilerplate for different type of message processing on the user end which is really a bad thing.
I imagine an additional proc macro can be introduced for packing message types into an enum and alter the handle methods, combining them into one gaint handle method.
This way we would have a pretty similar API as we have now and get the benefit of static dispatch. The downside I can think of is more code would be generated and bloating could be an issue for some usecases and a complex proc macro would add fragmentation for maintenance.

**Comment by fMeow** [comment]
I don't think this a good idea.

 The `Addr<MessageType>` adds more boilerplate and can cause confusion when a `MessageType` is handled in multiple `Actor`. I don't personally think it worthy to add such complexity for elimination of trait objects.

**Comment by robjtede** [comment]
General consensus looks like a no for this. Any other ideas on more concrete proposals should open a new issue.
