### ISSUE TITLE
Feature: PipelinedResponse

### ISSUE THREAD

**Issue by Diggsey** [actix/actix#368]
This would work similarly to `AtomicResponse`, but it would be constructed from two arguments: a `ResponseActFuture<Output = T>` and an `F: Fn(T) -> ResponseActFuture`.

The future corresponds to completing the request processing, and the function corresponds to sending the response. Only one "request" future can be spawned to an actor at once, and only one "response" future can be spawned to an actor at once, but there could be both a request and response future at the same time. Additionally, the order in which responses are spawned is guaranteed to be the same as the order of requests.

**Comment by fakeshadow** [comment]
This is not desireable at actix level. 

You need extra state or extra queue to track the different responses types. And extra branch to match on every actor poll.
`AtomicResponse` works because it's just an alias type for calling `Context::wait` which have it's own task queue.
Adding more states and/or task queue would further bloat the actor and make it have more runtime cost.

This is not a problem if the feature is a widely used one but for niche use case it's just extra cost for majority.
