### ISSUE TITLE
actix::io::FramedWrite cannot be shared across threads

### ISSUE THREAD

**Issue by GopherJ** [actix/actix#371]
It seems that actix assumes everything happen in `single thread` to get better performance.

However, I don't really understand why `actix::io::FramedWrite` cannot be shared across threads...

It causes that `awc::ws::Client` can only be used in single thread environment. It brings many limits.

Say that you need to share an actor address across threads but because `actix::io::FramedWrite` doesn't implement `Send` and `Sync` you are not able to do so....

**Edit**:

what I want to say is: `share an actor across threads`, not ` share an actor address across threads`, it's a typo

**Comment by GopherJ** [comment]
https://github.com/actix/actix/blob/b7c7237223dae46d27426799a48b4354c4376f54/src/io.rs#L59

**Comment by fMeow** [comment]
Actually I can spawn a actor with `AsyncContext` in another thread and clone its `addr` to actor in the main thread (I regard the thread where `actix::System` run as the main thread).

So the `actix::io::FramedWrite` might not be the reason you fail to share the adddress of an actor across threads.

**Comment by GopherJ** [comment]
@fMeow I have nerver said that I fail to share the address of an actor. I said:

```
It causes that awc::ws::Client can only be used in single thread environment. It brings many limits.
```

Client is an actor not an address, it's reasonable to have `Rc` in actix-web, but I don't think we should overuse `Rc` in actix which is an actor framework, not designed just for actix-web

**Comment by fMeow** [comment]
I suppose what you called `awc::ws::Client` refers to `Framed<BoxedSocket, Codec>` retruned by [`awc::ws::WebsocketsRequest::connect`](https://docs.rs/awc/2.0.0-alpha.2/awc/ws/struct.WebsocketsRequest.html#method.connect). 

It's not a `awc::Client` struct or something like that, it's something that implement both [`futures::Stream`](https://docs.rs/futures/0.3.5/futures/prelude/trait.Stream.html) and [`futures::Sink`](https://docs.rs/futures/0.3.5/futures/prelude/trait.Sink.html) trait. We can clone it for every single thread/`Future` With a `awc::Client`, whilist a `Framed` cannot.

You mentioned `actix::io::FramedWrite`, so I think you split the `Framed<BoxedSocket, Codec>`  into `SplitStream` and `SplitSink`, attach the stream to an actor, and wrap the `SplitSink` with `actix::io::FramedWrite`. And now you want to move it between thread/`Future`.

If I'm right, it's not because `actix::io::FramedWrite` but the `Framed<BoxedSocket, Codec>` itself that fail to send across thread/`Future`. It seem impossible to achive what you want since `BoxedSocket` is `!Send`. I will suggest to wrap the `SplitSink` in an actor, and use send `actix::Message` to this `actix::Actor` to interact with it. And this is the solution that I am currently using (see [actix example on websocket client](https://github.com/actix/examples/blob/master/websocket/src/client.rs)).

But yes, `actix::io::FramedWrite` cannot be shared across threads since it need to interact with the runtime or `AsyncContext`. Thus it seem pointless to make it `Send`. If you don't need to use the self reference of an actor or interact with the context of an acotr, you can use the `tokio` version of [`FramedWrite`](https://docs.rs/tokio-util/0.3.1/tokio_util/codec/struct.FramedWrite.html) which is `Sync` and `Send` instead of the one with actor support.

**Comment by fakeshadow** [comment]
awc is not thread safe from top to bottom. There are far more parts are not safe the share between threads than `FramedWrite`.
The connection pool is not thread safe. The connectors are not thread safe. etc

There is no limiation to begin with as it's supposed to work this way. You can use other thread safe clients if you want.
