### ISSUE TITLE
Hey,all,I have one question.

### ISSUE THREAD

**Issue by phil-skillwon** [actix/actix#566]
Is this project still being maintained? It seemed to be in a halted state before. Can I confidently use actix in my project without worrying about it ceasing maintenance?

**Comment by robjtede** [comment]
This actor framework is in passive maintenance mode. (We should make it clear in the manifest that this is the case.)

What this means is that PRs will be considered and releases will be made for security issues but the Actix team is not actively working on features for this crate. `actix` doesn't fix very well into today's modern async/await landscape and since `actix` isn't actually used to power Actix Web any more, we're not interested in the time investment it would take to completely rework it.

**Comment by robjtede** [comment]
If you want the benefits of the actor model plus the benefits of async/await I'd suggest reading this https://ryhl.io/blog/actors-with-tokio

If it's WebSocket support in Actix Web that's brought you to `actix` then I'd recommend the [`actix-ws`](https://crates.io/crates/actix-ws) crate which provides a modern interface for WebSockets.
